Dress.delete_all
Dress.create(:dress_id => 100, :dress_name => "Olive", :dress_price => 80, :dress_image => "https://s7.jcrew.com/is/image/jcrew/A1743_RD6501_m?$pdp_fs418$")
Dress.create(:dress_id => 101, :dress_name => "Charlotte", :dress_price => 100, :dress_image => "https://s7.jcrew.com/is/image/jcrew/93100_PK6107_m?$pdp_fs418$")
Dress.create(:dress_id => 102, :dress_name => "Zoey", :dress_price => 120, :dress_image => "https://s7.jcrew.com/is/image/jcrew/05803_RD6523_m?$pdp_fs418$")
Dress.create(:dress_id => 103, :dress_name => "Lily", :dress_price => 150, :dress_image => "https://s7.jcrew.com/is/image/jcrew/03140_OR5513_m?$pdp_fs418$")
Dress.create(:dress_id => 104, :dress_name => "Chloe", :dress_price => 120, :dress_image => "https://s7.jcrew.com/is/image/jcrew/04988_NA6814_m?$pdp_fs418$")
Dress.create(:dress_id => 105, :dress_name => "Kenzie", :dress_price => 80, :dress_image => "https://s7.jcrew.com/is/image/jcrew/09726_GY6336_m?$pdp_fs418$")

Fabric.delete_all
Fabric.create(:fabric_id => 200, :fabric_name => "Rayon", :fabric_color => "Blush", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/93100_PK6107_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 201, :fabric_name => "Cotton", :fabric_color => "Navy Blue", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/04988_BL8837_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 202, :fabric_name => "Jersey", :fabric_color => "Black", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/04988_BK0001_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 203, :fabric_name => "Polyester", :fabric_color => "Maroon", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/04988_RD5818_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 204, :fabric_name => "Rayon", :fabric_color => "Graphite", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/04988_GY6529_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 205, :fabric_name => "Lace", :fabric_color => "Poppy", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/A1743_RD6501_sw?$pdp_sw20$")
Fabric.create(:fabric_id => 206, :fabric_name => "Rayon", :fabric_color => "Red", :fabric_image => "https://s7.jcrew.com/is/image/jcrew/05803_RD6523_sw?$pdp_sw20$")

Dressfabric.delete_all
Dressfabric.create(:dress_id => 100, :fabric_id => 200)
Dressfabric.create(:dress_id => 100, :fabric_id => 201)
Dressfabric.create(:dress_id => 100, :fabric_id => 202)
Dressfabric.create(:dress_id => 100, :fabric_id => 203)
Dressfabric.create(:dress_id => 100, :fabric_id => 204)
Dressfabric.create(:dress_id => 100, :fabric_id => 205)
Dressfabric.create(:dress_id => 101, :fabric_id => 200)
Dressfabric.create(:dress_id => 101, :fabric_id => 201)
Dressfabric.create(:dress_id => 101, :fabric_id => 202)
Dressfabric.create(:dress_id => 101, :fabric_id => 203)
Dressfabric.create(:dress_id => 101, :fabric_id => 204)
Dressfabric.create(:dress_id => 101, :fabric_id => 206)
Dressfabric.create(:dress_id => 102, :fabric_id => 200)
Dressfabric.create(:dress_id => 102, :fabric_id => 201)
Dressfabric.create(:dress_id => 102, :fabric_id => 202)
Dressfabric.create(:dress_id => 102, :fabric_id => 203)
Dressfabric.create(:dress_id => 102, :fabric_id => 204)
Dressfabric.create(:dress_id => 102, :fabric_id => 206)
Dressfabric.create(:dress_id => 103, :fabric_id => 200)
Dressfabric.create(:dress_id => 103, :fabric_id => 201)
Dressfabric.create(:dress_id => 103, :fabric_id => 202)
Dressfabric.create(:dress_id => 103, :fabric_id => 203)
Dressfabric.create(:dress_id => 103, :fabric_id => 204)
Dressfabric.create(:dress_id => 103, :fabric_id => 205)
Dressfabric.create(:dress_id => 103, :fabric_id => 206)
Dressfabric.create(:dress_id => 104, :fabric_id => 200)
Dressfabric.create(:dress_id => 104, :fabric_id => 201)
Dressfabric.create(:dress_id => 104, :fabric_id => 202)
Dressfabric.create(:dress_id => 104, :fabric_id => 203)
Dressfabric.create(:dress_id => 104, :fabric_id => 204)
Dressfabric.create(:dress_id => 104, :fabric_id => 206)
Dressfabric.create(:dress_id => 105, :fabric_id => 200)
Dressfabric.create(:dress_id => 105, :fabric_id => 201)
Dressfabric.create(:dress_id => 105, :fabric_id => 202)
Dressfabric.create(:dress_id => 105, :fabric_id => 203)
Dressfabric.create(:dress_id => 105, :fabric_id => 204)
Dressfabric.create(:dress_id => 105, :fabric_id => 205)
Dressfabric.create(:dress_id => 105, :fabric_id => 206)

Review.delete_all
Review.create(:dress_id => 100, :review_rating => 4, :review => "Great Dress!")
Review.create(:dress_id => 101, :review_rating => 5, :review => "Perfect Fit")
Review.create(:dress_id => 102, :review_rating => 3, :review => "Color was a little off")
Review.create(:dress_id => 103, :review_rating => 4, :review => "Many compliments")
Review.create(:dress_id => 104, :review_rating => 2, :review => "Runs small")
Review.create(:dress_id => 105, :review_rating => 5, :review => "Exactly what I expected")
Review.create(:dress_id => 100, :review_rating => 4, :review => "Great fit, color a bit off")
Review.create(:dress_id => 101, :review_rating => 5, :review => "Bride was ecstatic")
Review.create(:dress_id => 102, :review_rating => 2, :review => "Didn’t fit right")
Review.create(:dress_id => 103, :review_rating => 5, :review => "Look great in photos")
Review.create(:dress_id => 104, :review_rating => 2, :review => "Cheap material")
Review.create(:dress_id => 105, :review_rating => 5, :review => "Loved it!")
